# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2919a6b7d4edba34b649a378cdd418bb4fe956d6718849fc4a6b66fa9458d801ddf36302455f47cfbc84fbc99faec075c3bb30106640a270afd3a86449638e1c

test:
  secret_key_base: a2e968012492099939fbe9388683daba3c87e16af1475a681885fab9ab3ca145a844a0aa6fb4f04bc0f3e52a2fb5824185508a31a576d8a64469f239024af3d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
